{% set version = "0.0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-purrrlyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/purrrlyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/purrrlyr/purrrlyr_{{ version }}.tar.gz
  sha256: 085a8f691eb1ee24fd3a941c2042a80c480064bf2258263b0b911fa066438062

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-dplyr >=0.8.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-dplyr >=0.8.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.2

test:
  commands:
    - $R -e "library('purrrlyr')"           # [not win]
    - "\"%R%\" -e \"library('purrrlyr')\""  # [win]

about:
  home: https://github.com/hadley/purrrlyr
  license: GPL-3.0-only
  summary: Some functions at the intersection of 'dplyr' and 'purrr' that  formerly lived in 'purrr'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: purrrlyr
# Title: Tools at the Intersection of 'purrr' and 'dplyr'
# Version: 0.0.5
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "ctb"), person("RStudio", role = "cph") )
# Description: Some functions at the intersection of 'dplyr' and 'purrr' that  formerly lived in 'purrr'.
# License: GPL-3 | file LICENSE
# LazyData: true
# Imports: magrittr (>= 1.5), dplyr (>= 0.8.0), purrr (>= 0.2.2), Rcpp
# Suggests: testthat, covr
# LinkingTo: Rcpp, BH
# URL: https://github.com/hadley/purrrlyr
# BugReports: https://github.com/hadley/purrrlyr/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-03-15 18:10:18 UTC; lionel
# Author: Lionel Henry [aut, cre], Hadley Wickham [ctb], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-03-15 23:40:02 UTC
