# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Lj2jqOnTHDBmyop1Z8AdAQ/5aCMRG+nhthphSX0zuq2BVr+fHw3RKNsnfRplek0pHojyemb+ZxIsekk7pmAvCBHTdRFGgS+LJx2Me53ysYmCkda3NsYFcd3i2m8eikYufMS8D5Wk8j2k3NTVoBGYzHLaqsMOaZ8fyggfYiBch60lQZUBnO2QigiP6SddmU6oENphIpfvTAFCJ+PwEFJC2N9H/Kd8BrMoDEKUvEtchcsHs+cDAJFBSKrtYjFPR9c/lO3qRPgT/U1U4NzelQD+ZhT5xA6wySNgokV+LwK3Gwg/5DvCeauIIgN43WP4BFbBYosD8vVZOSLSU9XJ8wO2G+1iS7z6Lv/eIH0tJWP5AdYdd41rVYDVE6vS6cpQL7RxV8LhJUWlgowdtYmJTbyWt36cRO0lENrXNIxzRM7A27N4hc7/trgQiJTjZwcVyOKomjjBcVoXoipO33A9Bq7/QYM5VwjmW/NFRmFAR8DtgEAZTKeY9QPUgqJ6o0inxDjx+r9IFAfYwgr2NXOWUiDQQIhz5jz5EJtp9Rj2nvn+d2Z0ShEB7WMvjSx9iBFzJDCqcbW/w+kt9CWZBoZeWmKALk8MT3GSqb7WZ/Pi3gMU/NHF/AxFneqa6pmPktWD8ltD7gL608AHtyWxOlnU8oAfYHZKRklmwMJl5NJo0PC06H0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
